gui:
  mainPanelSplitMode: 'horizontal' # one of 'horizontal' | 'flexible' | 'vertical'
git:
  autoRefresh: true
  autoFetch: true
  disableForcePushing: true
  autoForwardBranches: none
  commit:
    autoWrapCommitMessage: false
refresher:
  refreshInterval: 10 # File/submodule refresh interval in seconds. Auto-refresh can be disabled via option 'git.autoRefresh'.
  fetchInterval: 300 # Re-fetch interval in seconds. Auto-fetch can be disabled via option 'git.autoFetch'.
